spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Demo01?useSSL=false
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.gmail.com
    port: 587
    username: vishnukayahan708@gmail.com
    password: wzcvwtxulaascazx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8080

rabbitmq:
  queue:
    email:
      name: Rabbit_email_queue
  exchange:
    email:
      name: Rabbit_email_exchange
  binding:
    email:
      name: Rabbit_email_routing_key

logging:
  level:
    org:
      springframework:
        amqp: DEBUG
